name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build step 1
        run: echo 'This is a build job (steps) because it does not declare an environment'
        
  DeployReview:
    runs-on: ubuntu-latest
    needs: [Build]
    environment: review
    steps:
      - name: Deployment step, to review (Step 1)
        run: echo 'This is a job and set of setps which are considered being deployment to an environment (staging), it will show on GitHub'
  
  DeployStaging:
    runs-on: ubuntu-latest
    needs: [Build]
    environment: staging
    
    steps:
      - name: Deployment step, to staging (Step 1)
        run: echo 'This is a job and set of steps which are considered being a deployment to an environment, it will show on GitHub'
        
  DeployProduction:
    runs-on: ubuntu-latest
    needs: [Build, DeployStaging]
    environment: production
    
    steps:
      - name: Deployment step, to production (Step 1)
        run: echo 'This is a job and set of steps which are considered being a deployment to an environment, it will show on GitHub'
