name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build step 1
        run: echo This is a build job (steps) because it does not declare an environment
  
  DeployStaging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Deploy step 1
        run: echo This is a job and set of steps which are considered being a deployment to an environment, it will show on GitHub
