name: CICD

on:
  push:
    branches: [staging, main]
  pull_request:
    branches: [staging]
    types: [opened]
  workflow_dispatch:

jobs:
  Build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Build step 1
        run: echo 'This is a build job (steps) because it does not declare an environment'
        
  DeployReview:
    name: Deploy to Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: review
      url: http://example.com/#review
    steps:
      - name: Deployment step, to review (Step 1)
        run: echo 'This is a job and set of setps which are considered being deployment to an environment (staging), it will show on GitHub'
  
  DeployStaging:
    name: Deploy to Staging
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: staging
      url: http://example.com/#staging
    
    steps:
      - name: Deployment step, to staging (Step 1)
        run: echo 'This is a job and set of steps which are considered being a deployment to an environment, it will show on GitHub'
        
  DeployProduction:
    name: Deploy to Production
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: [Build, DeployStaging]
    environment:
      name: production
      url: http://example.com/#production
    
    steps:
      - name: Deployment step, to production (Step 1)
        run: echo 'This is a job and set of steps which are considered being a deployment to an environment, it will show on GitHub'
